# Generated by Django 5.0.6 on 2024-06-30 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="QuizQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField()),
                ("topic_id", models.IntegerField()),
                ("difficulty", models.CharField(max_length=50)),
                ("choice_a", models.TextField()),
                ("choice_b", models.TextField()),
                ("choice_c", models.TextField()),
                ("choice_d", models.TextField()),
                ("correct_answer", models.TextField()),
                ("explanation", models.TextField()),
            ],
        ),
    ]
